name: alquilemos_enla_playa
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  cloud_firestore: ^4.9.2
  equatable: ^2.0.5
  firebase_core: ^2.16.0
  flow_builder: ^0.0.9
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.1.0 
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.13
  intl: ^0.18.0
  bloc: ^8.1.2
  go_router: ^11.1.1
  formz: ^0.6.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf